version: '3.8'

services:
  postgres-dev:
    image: postgres:15-alpine
    container_name: printpilot_db_dev
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-printpilot}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-printpilot_dev_123}
      POSTGRES_DB: ${DB_NAME:-printpilot_dev}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-printpilot} -d ${DB_NAME:-printpilot_dev}"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-test:
    image: postgres:15-alpine
    container_name: printpilot_db_test
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${TEST_DB_USER:-printpilot_test}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD:-printpilot_test_123}
      POSTGRES_DB: ${TEST_DB_NAME:-printpilot_test}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TEST_DB_USER:-printpilot_test} -d ${TEST_DB_NAME:-printpilot_test}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-dev:
    image: redis:7-alpine
    container_name: printpilot_redis_dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD:-printpilot_redis_123} --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: printpilot_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres-dev
    environment:
      ADMINER_DEFAULT_SERVER: postgres-dev

volumes:
  postgres_dev_data:
    driver: local
  postgres_test_data:
    driver: local