-- CreateTable
CREATE TABLE "inventory_transactions" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "type" TEXT NOT NULL,
    "itemType" TEXT NOT NULL,
    "itemId" TEXT NOT NULL,
    "quantity" INTEGER NOT NULL,
    "description" TEXT,
    "frameRequirementId" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "inventory_transactions_frameRequirementId_fkey" FOREIGN KEY ("frameRequirementId") REFERENCES "frame_requirements" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "system_config" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "companyName" TEXT,
    "companyLogo" TEXT,
    "companyEmail" TEXT,
    "companyPhone" TEXT,
    "companyAddress" TEXT,
    "companyNip" TEXT,
    "companyRegon" TEXT,
    "companyWebsite" TEXT,
    "defaultCurrency" TEXT NOT NULL DEFAULT 'PLN',
    "defaultTimezone" TEXT NOT NULL DEFAULT 'Europe/Warsaw',
    "businessHours" TEXT,
    "workingDays" TEXT,
    "emailNotifications" BOOLEAN NOT NULL DEFAULT true,
    "lowStockThreshold" INTEGER NOT NULL DEFAULT 10,
    "orderVolumeAlert" INTEGER NOT NULL DEFAULT 50,
    "notificationFrequency" TEXT NOT NULL DEFAULT 'REAL_TIME',
    "autoReorderEnabled" BOOLEAN NOT NULL DEFAULT false,
    "reorderLeadDays" INTEGER NOT NULL DEFAULT 7,
    "safetyStockPercent" INTEGER NOT NULL DEFAULT 20,
    "defaultSenderName" TEXT,
    "defaultSenderAddress" TEXT,
    "shippingMarkup" DECIMAL NOT NULL DEFAULT 0,
    "freeShippingThreshold" DECIMAL,
    "apaczkaAppId" TEXT,
    "apaczkaApiKey" TEXT,
    "apaczkaTestMode" BOOLEAN NOT NULL DEFAULT false,
    "companyPostalCode" TEXT,
    "dashboardLayout" TEXT NOT NULL DEFAULT 'DEFAULT',
    "itemsPerPage" INTEGER NOT NULL DEFAULT 20,
    "chartDateRange" INTEGER NOT NULL DEFAULT 30,
    "exportFormat" TEXT NOT NULL DEFAULT 'PDF',
    "adobeStockApiKey" TEXT,
    "adobeStockEnabled" BOOLEAN NOT NULL DEFAULT false,
    "webhookRetryCount" INTEGER NOT NULL DEFAULT 3,
    "syncBatchSize" INTEGER NOT NULL DEFAULT 50,
    "rushOrderSurcharge" DECIMAL NOT NULL DEFAULT 25.0,
    "maxDailyCapacity" INTEGER,
    "productionLeadDays" INTEGER NOT NULL DEFAULT 3,
    "orderConfirmationTemplate" TEXT,
    "shippingNotificationTemplate" TEXT,
    "lowStockEmailTemplate" TEXT,
    "primaryColor" TEXT NOT NULL DEFAULT '#3B82F6',
    "secondaryColor" TEXT NOT NULL DEFAULT '#6B7280',
    "logoPosition" TEXT NOT NULL DEFAULT 'TOP_LEFT',
    "customCss" TEXT,
    "autoBackupEnabled" BOOLEAN NOT NULL DEFAULT true,
    "backupFrequency" TEXT NOT NULL DEFAULT 'WEEKLY',
    "dataRetentionMonths" INTEGER NOT NULL DEFAULT 24,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "version" TEXT NOT NULL DEFAULT '1.0',
    "lastBackup" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
